### ISSUE TITLE
Support Reading IDAUSR config

### ISSUE THREAD

**Issue by stevemk14ebr** [oopsmishap/HexRaysPyTools#12]
When the plugin is placed inside of the IDAUSR folder (%APPDATA%\Hex-Rays\IDA Pro\plugins) (ida_diskio.get_user_idadir()) (https://hex-rays.com/blog/igors-tip-of-the-week-33-idas-user-directory-idausr/) the plugin fails to read its configuration correctly and throws and error at plugin load. Support placing the plugin in this folder as it's supperior to the IDA installation directory since it survives IDA upgrades and reinstalls.

**Comment by oopsmishap** [comment]
Thank you for raising this, someone also recently told me that this was an issue but as it was just said in passing I had forgotten to change this.

I have rectified this in the latest commit (e92fdcf) along with a slight refactor to how the settings functionality worked.

Let me know if this solves the issue you faced.

**Comment by stevemk14ebr** [comment]
works perfectly, thanks! Side note, i've switched to using your fork instead of the old one, thanks for working on it this is one of my favorite plugins :)

https://github.com/stevemk14ebr/RETools/tree/master/IdaScripts/plugins
